name: Publish plugin

on:
  repository_dispatch:
    types: build_image

jobs:
  build:
    env:
      REF: ${{ github.event.client_payload.ref }}
      WORKSPACE: ${{ github.event.client_payload.workspace }}
      TAG: ${{ github.event.client_payload.tag }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Checkout code
        run: |
          git clone https://github.com/redhat-developer/rhdh-plugins
          cd rhdh-plugins
          git fetch origin $REF:workwork
          git checkout workwork
      - name: Build workspace
        run: |
          cd workspaces/$WORKSPACE
          yarn
          yarn tsc
          yarn build:all
          npx @janus-idp/cli@latest package package-dynamic-plugins --tag $TAG
      - name: Push image
        run: |
          podman login -u="$USERNAME" -p="$TOKEN" quay.io
          podman push $TAG
